# Generated by Django 6.0.6 on 2026-06-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstop',
            name='latitude',
            field=models.FloatField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelstop',
            name='longitude',
            field=models.FloatField(db_index=True, null=True),
        ),
    ]
