# Generated by Django 6.0.6 on 2026-06-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0002_alter_fuelstop_latitude_alter_fuelstop_longitude'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelstop',
            index=models.Index(fields=['latitude', 'longitude'], name='route_plann_latitud_a726db_idx'),
        ),
    ]
